# Generated by Django 4.2.2 on 2023-06-26 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('horas', models.IntegerField(null=True)),
                ('profesor', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('horas', models.IntegerField(null=True)),
                ('herramientas', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='veterinario',
            name='consultorio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinarios.consultorio'),
        ),
        migrations.AddField(
            model_name='veterinario',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veterinarios.especialidad'),
        ),
    ]
