# Generated by Django 4.2.2 on 2023-06-26 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0002_consultorio_especialidad_veterinario_consultorio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultorio',
            old_name='profesor',
            new_name='propietario',
        ),
    ]
