# Generated by Django 4.2.2 on 2023-06-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarios', '0003_rename_profesor_consultorio_propietario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultorio',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
